apiVersion: v1
kind: ConfigMap
metadata:
  name: sck-ext-conf-cm
  namespace: default
data:
  application.yaml: |-
    app:
      version: '1.0'
    logging:
      level:
        root: info
    management:
      endpoints:
        web:
          exposure:
            include: '*'
    server:
      port: 8080
    spring:
      cloud:
        kubernetes:
          discovery:
            all-namespaces: false
            namespaces:
              - default
          loadbalancer:
            mode: SERVICE
          reload:
            enabled: true
