apiVersion: v1
kind: Service
metadata:
  name: sck-app-svc
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sck-app
  type: ClusterIP
