apiVersion: v1
kind: ConfigMap
metadata:
  name: sck-app-conf-cm
  namespace: default
data:
  application.yml: |-
    spring:
      application:
        name: 'sck'
      config:
        import: 'kubernetes:'
      cloud:
        kubernetes:
          config:
            name: sck-ext-conf-cm
