apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sbk-app
  name: sbk-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sbk-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sbk-app
    spec:
      containers:
        - env:
            - name: TZ
              value: 'Asia/Shanghai'
          image: 'vizee/sbk:latest'
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: http-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          name: sbk-app
          ports:
            - containerPort: 8080
              name: http-port
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: http-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 1Gi
          volumeMounts:
            - mountPath: /app/config
              name: app-config-vol
            - mountPath: /etc/localtime
              name: volume-localtime
      volumes:
        - configMap:
            defaultMode: 420
            name: sbk-app-conf-cm
          name: app-config-vol
        - hostPath:
            path: /etc/localtime
          name: volume-localtime
